apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    app: {{ .Release.Name }}
    name: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    name: {{ .Release.Name }}
  minReplicaCount: 0
  cooldownPeriod: 10
  maxReplicaCount: 10
  triggers:
{{ toYaml .Values.triggers | indent 3 }}
