image: karthik3030/queuefunckeda:latest
functions:
- queueExample 
secrets:
  AzureWebJobsStorage: "DefaultEndpointsProtocol=https;AccountName=azfuncpowershela333;AccountKey=l2qN5Tglh9lnxoYO/00rxItyrHWDe5VvgI2qmFtKs+EvWzd5aF6lWWKlf8Ik2JVDLaPZUoiy+rn0+BrG7kY6lA==;EndpointSuffix=core.windows.net"
  FUNCTIONS_WORKER_RUNTIME: python
triggers:
- metadata:
    connection: AzureWebJobsStorage
    direction: in
    name: msg 
    queueName: python-queue-items
    type: queueTrigger
  type: azure-queue
